//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Menu()
        {
            this.ZakaznBludaNew = new HashSet<ZakaznBludaNew>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> Weight { get; set; }
        public string Structure { get; set; }
        public Nullable<int> Calories { get; set; }
        public int Section { get; set; }
        public Nullable<double> Price { get; set; }
    
        public virtual Sections Sections { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ZakaznBludaNew> ZakaznBludaNew { get; set; }
    }
}
