//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class k_kiri11Entities : DbContext
    {
        public k_kiri11Entities()
            : base("name=k_kiri11Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Employees> Employees { get; set; }
        public virtual DbSet<Menu> Menu { get; set; }
        public virtual DbSet<Restaurants> Restaurants { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<Sections> Sections { get; set; }
        public virtual DbSet<Vxod> Vxod { get; set; }
        public virtual DbSet<RegistrationZakaza> RegistrationZakaza { get; set; }
        public virtual DbSet<ZakaznBluda> ZakaznBluda { get; set; }
        public virtual DbSet<GiftSertificate> GiftSertificate { get; set; }
        public virtual DbSet<SaleCarts> SaleCarts { get; set; }
        public virtual DbSet<Table> Table { get; set; }
    }
}
