//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegistrationZakaza
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RegistrationZakaza()
        {
            this.ZakaznBludaNew = new HashSet<ZakaznBludaNew>();
        }
    
        public int Id { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public Nullable<int> ZakazBludaId { get; set; }
        public Nullable<int> NumberTable { get; set; }
        public Nullable<System.DateTime> DateOpen { get; set; }
        public Nullable<System.DateTime> DateClose { get; set; }
        public Nullable<int> Total { get; set; }
        public Nullable<int> GiftSertificateId { get; set; }
        public Nullable<int> SaleCart { get; set; }
        public Nullable<bool> ZakazZakrit { get; set; }
    
        public virtual Employees Employees { get; set; }
        public virtual GiftSertificate GiftSertificate { get; set; }
        public virtual SaleCarts SaleCarts { get; set; }
        public virtual Table Table { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ZakaznBludaNew> ZakaznBludaNew { get; set; }
    }
}
