//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZakaznBluda
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ZakaznBluda()
        {
            this.RegistrationZakaza = new HashSet<RegistrationZakaza>();
        }
    
        public int Id { get; set; }
        public Nullable<int> FirstBludo { get; set; }
        public Nullable<int> SecondBludo { get; set; }
        public Nullable<int> ThirtdBludo { get; set; }
        public Nullable<int> FourthBludo { get; set; }
        public Nullable<int> FifthBludo { get; set; }
        public Nullable<int> Total { get; set; }
    
        public virtual Menu Menu { get; set; }
        public virtual Menu Menu1 { get; set; }
        public virtual Menu Menu2 { get; set; }
        public virtual Menu Menu3 { get; set; }
        public virtual Menu Menu4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RegistrationZakaza> RegistrationZakaza { get; set; }
    }
}
