//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZakaznBludaNew
    {
        public int Id { get; set; }
        public Nullable<int> IdBluda { get; set; }
        public Nullable<int> IdZakaza { get; set; }
        public Nullable<int> Count { get; set; }
        public Nullable<float> Price { get; set; }
        public string NameBluda { get; set; }
    
        public virtual Menu Menu { get; set; }
        public virtual RegistrationZakaza RegistrationZakaza { get; set; }
    }
}
